### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by sfhacker** [chhdao/Baseee#1]
First of all, try to use English as much as possible. It doesn't hurt or bite.

Just downloaded master branch and I get this error message:

![image](https://user-images.githubusercontent.com/25817529/94999062-57f04f00-0602-11eb-9136-046227b6c18d.png)

**Comment by chhdao** [comment]
Get! But it compiles successfully on my computer. I try three surroundings to compiles and success.

- WSL(Debian GNU/Linux 10 (buster) on Windows 10 x86_64) & g++ (Debian 8.3.0-6) 8.3.0 & cmake version 3.13.4 & GNU Make 4.2.1
- x86_64-pc-cygwin & g++ (GCC) 10.2.0 & cmake version 3.17.3 & GNU Make 4.3
- The The latest Visual Studio c++ surroundings    
Maybe you need to provide more information.

**Comment by sfhacker** [comment]
We use GCC 10.2.0 x64 on MSYS/MinGW environments.
Can you advise how to fix the compilation issue?

Regards.

**Comment by chhdao** [comment]
Thanks. Maybe you need to recompile with the latest version.

**Comment by sfhacker** [comment]
Are you sure?
I compiled master branch!

Can you advise how to fix the compilation error?

**Comment by chhdao** [comment]
If possible, please attach the complete error message. Thanks a lot.

**Comment by chhdao** [comment]
And the master was update today.

**Comment by sfhacker** [comment]
What is your mother tongue?

**Comment by chhdao** [comment]
En......Chinese.

**Comment by chhdao** [comment]
Maybe you can continue to compile and use the latest code immediately. The Github Action test was very successful. If the error persists, please replace the compiler.  
Here is first release version.
https://github.com/chhdao/Baseee/releases/tag/V1.0.0-Release
